#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-IO-Socket-Timeout
Version  : 0.32
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/D/DA/DAMS/IO-Socket-Timeout-0.32.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/D/DA/DAMS/IO-Socket-Timeout-0.32.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libi/libio-socket-timeout-perl/libio-socket-timeout-perl_0.32-1.debian.tar.xz
Summary  : 'IO::Socket with read/write timeout'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-IO-Socket-Timeout-license
Requires: perl-IO-Socket-Timeout-man
Requires: perl(Module::Build::Tiny)
Requires: perl(PerlIO::via::Timeout)
Requires: perl(Test::TCP)
BuildRequires : perl(Module::Build::Tiny)
BuildRequires : perl(PerlIO::via::Timeout)
BuildRequires : perl(Test::TCP)

%description
This archive contains the distribution IO-Socket-Timeout,
version 0.32:
IO::Socket with read/write timeout

%package license
Summary: license components for the perl-IO-Socket-Timeout package.
Group: Default

%description license
license components for the perl-IO-Socket-Timeout package.


%package man
Summary: man components for the perl-IO-Socket-Timeout package.
Group: Default

%description man
man components for the perl-IO-Socket-Timeout package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n IO-Socket-Timeout-0.32
mkdir -p %{_topdir}/BUILD/IO-Socket-Timeout-0.32/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/IO-Socket-Timeout-0.32/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-IO-Socket-Timeout
cp LICENSE %{buildroot}/usr/share/doc/perl-IO-Socket-Timeout/LICENSE
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/IO/Socket/Timeout.pm

%files license
%defattr(-,root,root,-)
/usr/share/doc/perl-IO-Socket-Timeout/LICENSE

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/IO::Socket::Timeout.3
